### ISSUE TITLE
Duktape error when trying to run the exemple GainPlugin.

### ISSUE THREAD

**Issue by nicolas-ra** [nick-thompson/blueprint#107]
Hello,

I am trying to run the basic GainPlugin example, but i run into this duktape error : 

<img width="783" alt="Capture d’écran 2020-09-24 à 23 19 41" src="https://user-images.githubusercontent.com/49728072/94201558-75b00c80-febc-11ea-9d35-6e178b7d5d2b.png">

After hours of searching, I have 0 clue.

Juice v6.0.1

**Comment by JoshMarler** [comment]
Hey @nicolas-ra,

So I've tested this locally and the GainPlugin example seems to be fine. Are you certain you have followed the correct steps to build the bundle? i.e. ran `npm install` and `npm run build` in `blueprint/packages/juce-blueprint` followed by the same in `blueprint/examples/GainPlugin/Source/jsui` ?

If you've done this there may be some other issue going on.

If you run `npm run start` in `blueprint/examples/GainPlugin/Source/jsui` webpack will spit out an unminified/debug build. You could then run the app in Xcode again to hopefully get a little more context on that error from duktape.

If might be worth attaching your main.js bundle to this issue after doing the above and maybe one of us can take a quick look at the bundle to see if we can spot anything obviously wrong.

For reference I pulled and built the GainPlugin example from master this morning with no issues. Attached is my compiled main.js file for reference in case you have any obvious differences.
[main.txt](https://github.com/nick-thompson/blueprint/files/5281818/main.txt)

**Comment by JoshMarler** [comment]
@nicolas-ra , did you get to the bottom of this and/or are you able to build and run current master? If good let's close this.

**Comment by nick-thompson** [comment]
I think we're good to go ahead and close this. @nicolas-ra please feel free to re-open if your issue is not solved!
