### ISSUE TITLE
'Starting a new Project' documentation missing informations

### ISSUE THREAD

**Issue by nicolas-ra** [nick-thompson/blueprint#108]
Hello, 

I have been trying to setup blueprint in a blank new project generated with Juice v6.0.1.

This section from https://nick-thompson.github.io/blueprint/#/New_Project : 

```
class MainComponent   : public Component
{
public:
    //==============================================================================
    MainComponent()
    {
        addAndMakeVisible(appRoot);
        setSize(400, 300);
    }

    ~MainComponent();

    //==============================================================================
    void paint (Graphics&) override;

    void resized() override
    {
        appRoot.setBounds(getLocalBounds());
    }

private:
    //==============================================================================
    blueprint::ReactApplicationRoot appRoot;

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (MainComponent)
};
``` 

Does not say which file it should be in. After looking in my project I came to the conclusion that it is `PluginEditor.h`.

But my file is not quite the same as the one from the documentation.
My "`MainComponent`" (which is called `NewProjectAudioProcessorEditor`) doesn't inherit from `Component` but from `juce::AudioProcessorEditor` which seems to create the following issue when integrating the code :
<img width="968" alt="Capture d’écran 2020-09-24 à 22 19 36" src="https://user-images.githubusercontent.com/49728072/94202442-f0c5f280-febd-11ea-9d34-dde0b6bc0689.png">
 
Here is the full class  (`PluginEditor.h`) generated by JUCE v6.0.1 : 

```
#pragma once

#include <JuceHeader.h>
#include "PluginProcessor.h"

//==============================================================================
/**
*/
class NewProjectAudioProcessorEditor  : public juce::AudioProcessorEditor
{
public:
    NewProjectAudioProcessorEditor (NewProjectAudioProcessor&);
    ~NewProjectAudioProcessorEditor() override;

    //==============================================================================
    void paint (juce::Graphics&) override;
    void resized() override;

private:
    // This reference is provided as a quick way for your editor to
    // access the processor object that created it.
    NewProjectAudioProcessor& audioProcessor;

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (NewProjectAudioProcessorEditor)
};
```

I would really appreciate if someone could point me to the right direction. I have strong experience in React, but I'm very new to C++.

Thanks !

**Comment by nicolas-ra** [comment]
EDIT : 

I managed to solve it (files content below), however i know have a runtime error in the Xcode console : 
```
JUCE v6.0.1
2020-09-25 00:45:02.517391+0200 NewProject[6383:116636]   saved enable noise cancellation setting is the same as the default (=0)
JUCE Assertion failure in blueprint_EcmascriptEngine.cpp:113
(lldb) 
```

`PluginEditor.cpp` : 

```
#include "PluginProcessor.h"
#include "PluginEditor.h"

//==============================================================================
NewProjectAudioProcessorEditor::NewProjectAudioProcessorEditor (NewProjectAudioProcessor& p)
    : AudioProcessorEditor (&p), audioProcessor (p)
{
        // First thing we have to do is load our javascript bundle from the build
        // directory so that we can evaluate it within our appRot.
        juce::File sourceDir = juce::File(__FILE__).getParentDirectory();
        juce::File bundle = sourceDir.getChildFile("jsui/build/js/main.js");

        addAndMakeVisible(appRoot);
        appRoot.evaluate(bundle.loadFileAsString());

        setSize(400, 300);
}


NewProjectAudioProcessorEditor::~NewProjectAudioProcessorEditor()
{
}
```

`PluginEditor.h`:
```
#include <JuceHeader.h>
#include "PluginProcessor.h"

//==============================================================================
/**
*/
class NewProjectAudioProcessorEditor  : public juce::AudioProcessorEditor
{
public:
	NewProjectAudioProcessorEditor (NewProjectAudioProcessor&);
	~NewProjectAudioProcessorEditor();
 //==============================================================================
	void paint (juce::Graphics&){};

    void resized()
    {
        appRoot.setBounds(getLocalBounds());
    }
	
private:
    // This reference is provided as a quick way for your editor to
    // access the processor object that created it.
    NewProjectAudioProcessor& audioProcessor;
    blueprint::ReactApplicationRoot appRoot;

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (NewProjectAudioProcessorEditor)
};
```

**Comment by JoshMarler** [comment]
Hey @nicolas-ra, That error seems to suggest your JS bundle file doesn't exist at the location you've used. 

To diagnose I would suggest printing out the full bundle path with a `DBG` statement and then first checking that actually exist on disk. 

```
//==============================================================================
NewProjectAudioProcessorEditor::NewProjectAudioProcessorEditor (NewProjectAudioProcessor& p)
    : AudioProcessorEditor (&p), audioProcessor (p)
{
        // First thing we have to do is load our javascript bundle from the build
        // directory so that we can evaluate it within our appRot.
        juce::File sourceDir = juce::File(__FILE__).getParentDirectory();
        juce::File bundle = sourceDir.getChildFile("jsui/build/js/main.js");

        DBG(juce::String::formatted("JS Bundle Path: %s", bundle.getFullPathName()));

        addAndMakeVisible(appRoot);
        appRoot.evaluate(bundle.loadFileAsString());

        setSize(400, 300);
}
```

This should print the bundle file path being used to Xcode debug console and then you can double check is the path is correct and actually where your bundle exists. 

If it doesn't exist are you certain you have run the relevant `npm install` and `npm run build` commands to build your bundle? Note that Xcode doesn't currently do this step for you as part of the build process.

**Comment by JoshMarler** [comment]
Just a thought whilst checking in on this. It does look like your hitting an assert in the juce::File overload of `evaluate` despite calling `loadFileAsString`. Would be good to confirm if that is the case as it should be preferring the juce::String overload. So your path may actually be correct. I'll check that in the morning and I can throw up a fix if needed. In the meantime try passing `evaluate(bundle);` directly without the `loadFileAsString`.

**Comment by BabakSamimi** [comment]
I had the same issue, not using the `loadFileAsString()` seems to be a temporary workaround, as Josh wrote.

**Comment by JoshMarler** [comment]
@BabakSamimi, forgot about this! Will sanity check tomorrow and drop a fix if needed.

**Comment by nick-thompson** [comment]
This should all be sorted now as of #115. I'm going to mark as closed, please reopen if you still see any issues!
