### ISSUE TITLE
Add More Examples

### ISSUE THREAD

**Issue by jrlanglois** [nick-thompson/blueprint#125]
Would be cool to see more UI stuff to know what GUI components are available (and which aren't?), and also it would nice to give examples for handling mouse/touch/keyboard input.

Wishful thinking maybe: it would even be cool to have something similar to the DemoRunner from JUCE itself to give a sense of how it parallels...

**Comment by JoshMarler** [comment]
@jrlanglois, Totally!, I've actually got this in progress. A ComponentShowcase app which looks very much like the JUCE Demo. Hopefully this should land fairly soon. We'll hopefully use it as the test bed to iterate on new components for blueprint.

**Comment by HrvojeFER** [comment]
I posted an issue today about a project I'm working on and I would gladly add an example once I have a minimal viable product of it.

**Comment by nick-thompson** [comment]
I'm going to merge this with #18 and generally track the idea of more and better example projects there. @HrvojeFER if you still have an example of your current project, I'd love to see it!
