### ISSUE TITLE
Optimise Canvas implementation

### ISSUE THREAD

**Issue by JoshMarler** [nick-thompson/blueprint#133]
We've yet to spend anytime optimising our `CanvasView` implementation is this is almost certainly going to be a performance hot spot, particularly for dynamic components like sliders and meters. 

A likely hotspot here is going to be GC churn with all the `CanvasContext` objects passed between Native/JS. Are there some wins to be had here or ways to reduce GC churn? 

@nick-thompson, if you have any thoughts on this maybe we can add to the comments here and then tackle.

**Comment by nick-thompson** [comment]
Ok so here's an idea I came up with the other day that completely eliminates the canvas context native binding and I think should help with the GC churn. Below I'll list some scratch code, but the idea is essentially to shim a `CanvasRenderingContext` in such a way that we just build up a list of "draw commands," where each command is basically a tuple containing the command name and the arguments for that command. When it's time to draw, we reset our internal `drawCommands` array, call the user-supplied `onDraw`, build up a list of commands, and at the end we return that list over to native. The native side then runs a big `for` loop unpacking each tuple and affecting the appropriate write to the `Graphics` context.

```
class CanvasRenderingContext {
  constructor() {
    this.drawCommands = [];
  }

  reset() {
    this.drawCommands.length = 0;
  }

  set fillStyle(value) {
    this.drawCommands.push(["setFillStyle", value]);
  }

  set lineWidth(value) {
    this.drawCommands.push(["setLineWidth", value]);
  }

  fillRect(x, y, width, height) {
    this.drawCommands.push(["fillRect", x, y, width, height]);
  }

  ...etcetera
}

export class Canvas extends Component<CanvasProps, CanvasState> {
  constructor(props: CanvasProps) {
    super(props);

    this._context = new CanvasRenderingContext();
    this._onMeasure = this._onMeasure.bind(this);
    this._onDraw = this._onDraw.bind(this);

    this.state = {
      width: 0,
      height: 0
    };
  }

    _onDraw() {
    if (typeof this.props.onDraw === 'function') {
      this._context.reset();
      this.props.onDraw(this._context);
      return this._context.drawCommands;
    }
    return [];
  }

  render()...etc
}
```

And over on native we do (https://github.com/nick-thompson/blueprint/blob/master/blueprint/core/blueprint_CanvasView.h#L722):

```
auto commands = std::invoke(props["onDraw"].getNativeFunction(), nfArgs);

for (auto& cmd : commands->getArray()) {
    auto name = cmd[0].toString();
    // Maybe we have a std::map<juce::String, std::function<>> kind of situation here?
    drawMap[name](g /* the graphicsContext */, cmd[1], cmd[2]...) // dunno how to unpack this here exactly
}
```

Of course there's no better way to check this hypothesis than to profile what we currently have, write this up, profile it, and compare the results, but I have a hunch this could work nicely.

@JoshMarler what do you think?

**Comment by JoshMarler** [comment]
For reference. 

The vast majority of time profiling the GainPlugin example with a Canvas based slider is spent in two places. 

1. `juce::Graphics::drawImage`. This dominates CPU time. 
2. duktape functions in response to mouseDrag/dispatchEvent

We should be able to remove the need for rendering to an Image with the above change. I've also seen some intermittent UI lags when repeatedly moving a Slider on embedded targets. This is likely to be down to duktape mark-and-sweep spikes which may or may not be improved by reducing the number of temporary CanvasContext objects passed between JS and Native.

**Comment by stfufane** [comment]
Hey !
I wasn't looking at that particular issue but fell on something strange while debugging the GainPlugin with VS2019. The diagnostic tool showed that memory usage was constantly increasing (~1MB/3s). I was curious to see if it was linked to the debugger so I closed VS and launched the executable and watched memory usage on Windows task manager, and the issue was the same. 

I noticed that the increase was stopping when canvas was hidden. And indeed when I completely removed the canvas element from the example I didn't have the issue anymore.

So I tried to understand what's going on, I launched heap profiling and the result is that it's allocating "void" objects... I logged 12 seconds of not doing anything with the plugin and it counted 24k void objects (against 0 from almost all the other object types). The call stack indicates it comes from [this call](https://github.com/nick-thompson/blueprint/blob/master/blueprint/core/blueprint_CanvasView.h#L722)

I don't know much of what it's supposed to do but maybe it will look obvious to you :)

Good luck!

**Comment by JoshMarler** [comment]
@stfufane, Thanks for this!

So the GainPlugin example basically continually repaints on a canvas via a timer thread. So this is expected in some ways. Eventually that memory should be release when Duktape's garbage collection phase kicks in. I'm interested that you're seeing `void` objects to so thanks for that spot! That seems a little odd. @nick-thompson might understand better why you're seeing that at a first glance but I'll investigate. 

I think the key is to try and kill all these temporary objects with the implementation idea discussed above but the `void` object thing is definitely worth taking note of.

**Comment by JoshMarler** [comment]
Fix for this is now in master. Closing.
