### ISSUE TITLE
ASIO Support

### ISSUE THREAD

**Issue by HrvojeFER** [nick-thompson/blueprint#134]
Hello!

First of all, I wanted to say that I love this project and that I hope that it becomes a new standard for creating audio apps. I have had the same idea for a while now and I have started implementing it using cmake-js and JUCE. However, I am really reluctant to implement this all by myself when it's obvious to me that you guys will do a better job at it than I will.
With that said, I would like to ask if there exists an integration for ASIO drivers and if it doesn't, how would someone go about integrating ASIO into blueprint? I am trying to create a looping machine for beatboxing and low latency of ASIO drivers is key when it comes to that. 
I wrote some JUCE code in the past and I am fairly acquainted with the JUCE library and C++. I am using React and Typescript at my workplace, so blueprint seems like the perfect library for me! 
Also, I hope that I can contribute to blueprint at least for testing. :)

**Comment by nick-thompson** [comment]
Hello @HrvojeFER! 

> First of all, I wanted to say that I love this project and that I hope that it becomes a new standard for creating audio apps.

Thank you, I hope so too :D 

> With that said, I would like to ask if there exists an integration for ASIO drivers and if it doesn't, how would someone go about integrating ASIO into blueprint?

There's no direct integration of ASIO into blueprint, but blueprint really only concerns itself with assembling your project's user interface, and tries to remain as agnostic as possible to whatever else your project wants to do. I suspect you'd be able to start with a generic juce audio app, add blueprint, and then build out your ASIO integration on top of JUCE but independent of blueprint:

https://docs.juce.com/master/classAudioDeviceManager.html
https://docs.juce.com/master/tutorial_audio_device_manager.html

Let me know if that helps?

**Comment by HrvojeFER** [comment]
Thank you for your reply.
I was really hoping to use your library, but I soon discovered that I wanted to do things in reverse (sorry about the misunderstanding, I'm still a noob programmer). I finally realized that you made a library that renders React to JUCE, whereas I want to expose JUCE as an API to a JS app.
Thank you for your time and the best of luck to both of us. 😄
