### ISSUE TITLE
Add hitTest function prop to view

### ISSUE THREAD

**Issue by JoshMarler** [nick-thompson/blueprint#144]
@nick-thompson , I think I'm about to hit a use case where I need a component to respond to clicks only within a certain area. I.e. a circle drawn within a View's rect bounds.

Does this sound like a reasonable addition ? I can add if you think a hitTest prop is the right way to approach.

**Comment by nick-thompson** [comment]
Sounds like something that we can already do via composition ;)

```
class HitTestView extends React.Component {
  constructor(props) {
    super(props);

    this._onClick = this._onClick.bind(this);
  }

  _onClick(e) {
    if (customHitTest(e.x, e.y)) {
      if (typeof this.props.onClick === 'function') {
        this.props.onClick(e);
      }
      return;
    }

    e.preventDefault();
    e.stopPropagation();
  }

  render() {
    return (<View {...this.props} onClick={this._onClick}>{this.props.children}</View>);
  }
}
```

Then you just use `HitTestView` in place of `View` wherever you need that behavior, and of course implement the `customHitTest` helper

**Comment by JoshMarler** [comment]
Ah yeah OK neat. Seems a reasonable way to go. Think that's a thing worth having in the library itself or just documenting in some way ?

**Comment by nick-thompson** [comment]
It seems to me like more of a "how do I do X in React?" question than a question necessarily pertaining to blueprint/juce. So, I suppsoe I don't think it should be in the core library, and I also wonder if it's more of a third-party-blogpost candidate than something to be documented for blueprint. What do you think?

**Comment by JoshMarler** [comment]
Yeah. Agreed. More of a tutorial consideration. Cool. Cheers
