### ISSUE TITLE
Timers Polyfill

### ISSUE THREAD

**Issue by nick-thompson** [nick-thompson/blueprint#146]
Currently blocking #122.

This task is for implementing the following global timer functions within our EcmascriptEngine environment:
* `setTimeout`
* `setInterval`
* `clearTimeout`
* `clearInterval`

The task should be easy enough: in the EcmascriptEngine constructor and in its `reset` method, we just need to `registerNativeMethod` for the above mentioned functions. The implementations should match the web spec (e.g. https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setTimeout, although lets ignore the raw code string variant) where possible, and we can use juce's MultiTimer for actually keeping track of these timers: https://docs.juce.com/master/classMultiTimer.html.

Essentially I think we can just hang onto a `std::unordered_map<int, juce::var::NativeFunction>`, and when we receive a call to `setTimeout` we pick a new timerId (auto incrementing integer), put the callback into our unordered_map, call startTimer, and return the timerId to the js function call. Then in `timerCallback` we just look up the appropriate callback in the map and invoke it. I'm hand-waiving a bit here over how to identify whether we should run once or indefinitely, and how to handle the args, but that shouldn't be too hard.

@olidacombe I'll assign this to you per our conversation on Discord, but if you don't want it feel free to unassign yourself!

Edit: Hm I guess I can't assign you? But maybe you can assign yourself? If you want to tackle it, please do try to assign the issue to yourself.

Also Edit: this should probably wait until #145 merges or it will be quite messy. Or rebase the work off of #145 initially.

**Comment by olidacombe** [comment]
Hmmm, cool yes I want this, but can't see how to assign myself either...

**Comment by JoshMarler** [comment]
Ha sorry just testing whether you could assign other users. Feel free to remove yourself @olidacombe !

**Comment by nick-thompson** [comment]
Done in #188 🎉 !
