### ISSUE TITLE
Make juce_audio_processors an optional thing.

### ISSUE THREAD

**Issue by jrlanglois** [nick-thompson/blueprint#148]
Really, the juce_audio_processors module can be added by checking the module macro to see if it's available (this will mean optionally compiling your editor wrapper stuff with that).

![image](https://user-images.githubusercontent.com/1908886/101092141-2c003400-3587-11eb-868c-f28d4025fc1c.png)

**Comment by nick-thompson** [comment]
Hmm yea very good point... it's only the `GenericEditor` that has this dependency. We could easily omit the includes for `GenericEditor` if we know that the user doesn't want to include `juce_audio_processors`.

>  by checking the module macro to see if it's available

I don't follow you here but this sounds like the trick! Can you share more about that?

**Comment by jrlanglois** [comment]
Of course! https://github.com/nick-thompson/blueprint/pull/151

**Comment by nick-thompson** [comment]
Merged with #151!
