### ISSUE TITLE
Open question: Event support

### ISSUE THREAD

**Issue by nick-thompson** [nick-thompson/blueprint#15]
As it stands, Blueprint doesn't really have event support. There's a non-standard implementation of pushing events to JavaScript by registering global functions in your app bundle and calling them from C++, with one special case for finding view instances and pushing events right to them.

A proper implementation would catch events on visible view elements and create something like React's SyntheticEvent, then bubble that event up the virtual React element tree. React has a library for doing exactly this, but it is not a public library and likely way too unstable to try to rely on just yet. We could attempt to implement our own, but it would likely be incomplete for a while.

Another option is to provide a global EventBridge in Blueprint, which is already kind of implemented, and have every React element that needs events subscribe to the event bridge and filter events by some known id. This skips the question of bubbling and goes more the route of something like Rxjs, but still would benefit from some kind of SyntheticEvent wrapper. In this case, we would need to find a way for a React element to access the internal id of a given view from the renderer, so that it knows what to filter on. Not sure exactly how to provide that, and I'm also questioning whether that's the right idea in the first place... seems like it could be a design flaw.

I'll spend some time studying the React Native implementation and proposing ideas here

**Comment by JoshMarler** [comment]
@nick-thompson , at a point where this can be closed after the recent events work ? Or want to leave this open until we have covered all remaining events ? I.e. mouse over, mouse leave.

**Comment by nick-thompson** [comment]
Yes, definitely. With the above linked issues, we have pretty well resolved the open questions here. For documentation's sake: view events are dispatched into js much like the generic `dispatchEvent` hook, and those events are caught by an event replayer which takes the `ViewId` associated with the event and looks up the `ViewInstance` in the registry, then dispatches the event to that viewInstance and bubbles it up the parent tree. There is a lot of work to be done still enumerating the different event types and totally fleshing out the SyntheticEvent interface, but we've got our approach down, so closing this higher level issue.
