### ISSUE TITLE
Swap "typedef" for "using".

### ISSUE THREAD

**Issue by jrlanglois** [nick-thompson/blueprint#158]
It's the modern way...

**Comment by nick-thompson** [comment]
Sure, happy to make that update. Maybe this reveals the boundaries of my C++ knowledge here, but, practically, what's the difference?

**Comment by jrlanglois** [comment]
The declaration semantics change in a handful of subtle ways.

This article gives a great sense of it:
https://www.nextptr.com/tutorial/ta1193988140/how-cplusplus-using-or-aliasdeclaration-is-better-than-typedef

**Comment by nick-thompson** [comment]
Neat, got it. Thanks for the link!
