### ISSUE TITLE
Gain Example Build Failure

### ISSUE THREAD

**Issue by alisomay** [nick-thompson/blueprint#19]
I try to build the Gain example in Xcode Version 9.2 (9C40b). 
The example fails to build with the error message,

```
In file included from /Users/vallahiboyle/Desktop/JUCE/blueprint/examples/GainPlugin/JuceLibraryCode/include_blueprint.cpp:9:
In file included from ../../../../../blueprint/blueprint/blueprint.cpp:24:
../../../../../blueprint/blueprint/duktape/src-noline/duktape.c:29782:34: warning: implicit conversion loses integer precision: 'unsigned long' to 'duk_uint_fast32_t' (aka 'unsigned int') [-Wshorten-64-to-32]
                        match_val = (1UL << part_idx) + (1UL << (sep_idx + 9));  /* match against rule part/sep bits */
                                  ~ ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
In file included from /Users/vallahiboyle/Desktop/JUCE/blueprint/examples/GainPlugin/JuceLibraryCode/include_blueprint.cpp:9:
In file included from ../../../../../blueprint/blueprint/blueprint.cpp:27:
../../../../../blueprint/blueprint/blueprint.h:38:9: warning: 'YG_ENUM_BEGIN' macro redefined [-Wmacro-redefined]
#define YG_ENUM_BEGIN(name) enum name: unsigned
        ^
In file included from /Users/vallahiboyle/Desktop/JUCE/blueprint/examples/GainPlugin/JuceLibraryCode/include_blueprint.cpp:9:
In file included from ../../../../../blueprint/blueprint/blueprint.cpp:27:
In file included from ../../../../../blueprint/blueprint/blueprint.h:28:
../../../../../blueprint/blueprint/yoga/yoga/YGMacros.h:30:9: note: previous definition is here
#define YG_ENUM_BEGIN(name) enum name
        ^
clang: error: unable to execute command: Segmentation fault: 11
clang: error: clang frontend command failed due to signal (use -v to see invocation)
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin


```

**Comment by nick-thompson** [comment]
Ah, yikes, ok thanks for the report! I've been building on Xcode 9.4.1 just fine, I'll have to look into what's up with 9.2

**Comment by alisomay** [comment]
Please let me know if you want more info or I can help you in any way.

**Comment by alisomay** [comment]
I tried in Xcode Version 10.2.1 (10E1001) with OS X Mojave today and it builds with no issues.

**Comment by alisomay** [comment]
More news : 
Since the latest version of Xcode which is compatible with Sierra is Xcode 9.2 and the build failure happens with this one I tried to use Xcode 9.4.1 following this hack in Sierra.
[The instructions for the hack could be found in this link.](https://www.reddit.com/r/iOSProgramming/comments/89p5hw/cant_install_xcode_93_on_macos_sierra_10126/)
[To download any version of Xcode follow this link](https://developer.apple.com/download/more/)
In the end I have managed to make Xcode 9.4.1 work in Sierra!
Your examples build with no issues as you have stated in Xcode 9.4.1 .
I think Xcode 9.2 is the problem as you have stated.

**Comment by nick-thompson** [comment]
Ok, that's great news! So you're up and running with 9.4.1 on your own machine now?

I still want to resolve this issue correctly so that the next person who tries to build with 9.2 doesn't hit the trouble. I've spent some time looking into it and I'm realizing that I don't quite know how to effectively debug this. I'm sure I must be using a C++17 feature that whatever version of clang used in xcode 9.4 supports, but which the version of clang used in 9.2 does not, and I'm not sure how to find that feature.

If you have any ideas there, please let me know! But hopefully you can play with the more interesting stuff now that you have a working build

**Comment by alisomay** [comment]
Yes! That is true it is working and fortunately now I can make experiments with examples (thanks for providing them). 
If you think that it is C++17 and clang is the issue I can try to compile it with the latest gcc and see if anything goes wrong. Would you try also ?

**Comment by nick-thompson** [comment]
Great :)

If you want to spend the time to build with gcc, I'd be very grateful, but don't worry about it. I think there are probably higher priority problems to solve for now, and when I have more time I'll be able to really dig into this one. Thank you!

**Comment by alisomay** [comment]
Cool, thank you also. At least people can read this and go with the solution I found for myself. Good luck! When I have time I experiment with blueprint, I really think that bringing React to Juce has a future. Also my pursuit of porting paper.js continues slowly ;)

**Comment by nick-thompson** [comment]
It seems like this issue is more or less resolved, and likely that fewer and fewer people will be on Xcode9.2. I'm going to go ahead and close it as resolved, please feel free to reopen if you disagree.
