### ISSUE TITLE
TextInput native view

### ISSUE THREAD

**Issue by nick-thompson** [nick-thompson/blueprint#21]
See https://docs.juce.com/master/classTextEditor.html and https://facebook.github.io/react-native/docs/textinput.html

**Comment by JoshMarler** [comment]
@nick-thompson, quick question on this one. Do you envisage this basically being a wrapper around `juce::TextEditor` our would you imagine some composition of `View` and `Text` which handles keypress events and triggers an `onChange` prop/event?

**Comment by nick-thompson** [comment]
Yea, good question. I think we can go ahead with `juce::TextEditor`, and in general I want to mimic the behavior of a web's `<input type="text">` with things like support for a `placeholder` prop and a `minlength`, `maxlength`, etc: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/text.

We'll want both an `onChange` and an `onInput` event, and we'll want to follow React's controlled components model: https://reactjs.org/docs/uncontrolled-components.html. For example, if the user supplies a `value` prop, then we never render anything into that text editor other than the string supplied by that value prop.

We'll support `readonly` which is just an alias for `editable` basically, and yea `multiline` makes sense although I think I'd prefer to support it by allowing it on the native interface, but _not_ allowing it at the JS level: if a user wants a multiline texteditor they should use `<TextArea>`, which as far as implementation considered is equivalent to `<TextInput multiline>` but making this distinction at the user-facing API level will make it easier to support web.

Lastly, `font`, yea, I think the `<TextInput>` should more or less support the same text-style props as the `<Text>` element itself, if we can.

**Comment by nick-thompson** [comment]
Done in #217 by @utokusa!
