### ISSUE TITLE
Add continuous integration to project

### ISSUE THREAD

**Issue by tobanteAudio** [nick-thompson/blueprint#22]
During my first tests with `blueprint`, `npm` had a couple of errors which I could solve by deleting the `package-lock.json` files & running the `npm install` & `npm run build` commands with `yarn`:

```sh
yarn
yarn build
```

The problem could have probably been solved otherwise, but I thought this is a perfect example were CI could help and catch these kinds of errors early.

The project maintainer has to enable the services, but I can create the `appveyor.yml` (Windows) and `.travis.yml` (macOS & Linux).

This would also help with automatic documentation generation. See Issue #12 

Toby

**Comment by tobanteAudio** [comment]
I added Travis-ci support on my fork of `blueprint`: [tobanteAudio/blueprint](https://github.com/tobanteAudio/blueprint)

Trying to build it with the `xcode10.1` image I get the same error as explained above (in Windows). Here is the [output](https://travis-ci.org/tobanteAudio/blueprint/builds/582612104) of the build.

**Comment by tobanteAudio** [comment]
The problem seems to be the `npm install` command. It should be replaced by `npm ci`. 
See [here for an explanation](https://medium.com/better-programming/npm-ci-vs-npm-install-which-should-you-use-in-your-node-js-projects-51e07cb71e26). 

Although I'm not exactly sure why it works with one and not the other.

Maybe this should be in the README?

**Comment by nick-thompson** [comment]
Awesome! I love it, this looks great. A quick couple thoughts:

* Interesting about `npm install` vs `npm ci`. It makes sense as to why `yarn` works but `npm install` doesn't... I feel like `npm ci` should be npm's default (which would match `yarn`'s behavior). Let's use `npm ci` in the CI builds and also yea update the README. I suppose users who just want to use Blueprint should use `npm ci` but people who want to contribute and might consider updating the dependencies would want `npm install`
* Love that you have `pluginval` in there, that's a great idea
* I'm a little unsure about the VST3 build– did you have to add the SDK or is JUCE ok without it? I had originally unchecked that build just thinking that it would complicate the examples process for anybody who doesn't have the VST3 SDK locally. But if JUCE is cool without that, then let's keep it

**Comment by tobanteAudio** [comment]
The VST3 SDK is built into JUCE, so no extra dependencies.

**Comment by nick-thompson** [comment]
Ok perfect! I didn't know that.

I'd love to squash/merge your branch (https://github.com/tobanteAudio/blueprint/tree/travis-ci) here to get CI integrated, if you're interested? The only change I would ask is to re-save the BlueprintPlugin Projucer file with the version of JUCE pinned in the submodule (blueprint/ext/juce). I think it makes sense to keep those projects in sync.

**Comment by nick-thompson** [comment]
Done via github actions in #111!
