### ISSUE TITLE
compilation fails if JUCE_STRICT_REFCOUNTEDPOINTER is defined to 1

### ISSUE THREAD

**Issue by PentagramPro** [nick-thompson/blueprint#25]
This definition disables implicit conversion from ReferenceCountedObjectPtr to ReferencedType* which increases safety. Personally I like higher level of safety. If it contradicts your design, feel free to close this issue :)

Tried building on Windows with MSVS 2019.  See juce_ReferenceCountedObject.h for details.

**Comment by nick-thompson** [comment]
Hey @PentagramPro, sorry I'm just seeing this issue now! Thanks for reporting.

I'll look into this, pretty sure I know where that issue might arise, and I'm also pretty sure that I can take care of it cleanly during #9 which I'm working on now

**Comment by nick-thompson** [comment]
Fixed in edb738b767d11fa61c371bcd2ecc7f75ed384747 as part of the refactor for #9. I'm going to close this issue, please reopen if you see something wrong!
