### ISSUE TITLE
Pimpl for EcmascriptEngine and V8 Implementation

### ISSUE THREAD

**Issue by nick-thompson** [nick-thompson/blueprint#33]
Right now the EcmascriptEngine interface leaks (as in leaky abstraction) the `duk_context` as a private member variable. Long term I want the EcmascriptEngine to be a generic interface that can be implemented by any one of the various ES5+ compliant embedded js engines, and therefore the EcmascriptEngine interface should be totally implementation-independent. For that reason, I think it's a good idea to adopt the Pimpl pattern and move any duktape specifics into the pimpl class.

With that done, I'd love to take a stab at implementing the interface via V8 and providing the option to run Blueprint via V8 (both with and without the jit enabled): https://v8.dev/docs

**Comment by nick-thompson** [comment]
See #105.

I'd like to drop the idea of support V8 or JavascriptCore for now (potentially can revisit after we hit a stable 1.0 release) and aim strictly for clean duktape integration with the pimpl encapsulation

**Comment by JoshMarler** [comment]
@nick-thompson , Does this need to be beta?

**Comment by nick-thompson** [comment]
It doesn't need to be, no. There are two issues here: one of them is Pimpl'ing the EcmascriptEngine so that all the Duktape specifics are hidden inside the Pimpl, which I believe should ease #62 and some of the issues that @julianstorer saw when trying to compile with FAST_MATH. Part of me thinks this would be a nice beta feature, but I don't know if it should hold us up.

The second issue, which perhaps I'll open a separate github issue for, is that once we have a Pimpl paradigm in place, I'd love add a second pimpl implementation on top of V8, and then add a CMake `-DBLUEPRINT_USE_DUKTAPE` and a `-DBLUEPRINT_USE_V8` or something so that users can flip 1 flag in their CMake file to choose their javascript engine. (Or even build with V8 for desktop and Duktape for mobile or such). That one is _definitely_ not beta, but I think it would be awesome and would love to look into it or maybe get some help on it shortly after beta

**Comment by nick-thompson** [comment]
As of #145, the EcmascriptEngine interface has been cleaned up and is now properly Pimpled with Duktape underneath. I'll go ahead and mark this issue resolved, and open a separate issue for tracking a V8 Pimpl implementation
