### ISSUE TITLE
Reference to ‘AudioBuffer’ is Ambiguous

### ISSUE THREAD

**Issue by zigen** [nick-thompson/blueprint#36]
failed to build examples/BlueprintPlguin AU Plugin with XCode 11.4(11E146) on macOS 10.15.14 (Catalina)

the error shows 'Reference to ‘AudioBuffer’ is Ambiguous'.
JUCE causes this error on XCode11.4 and [already solved](https://forum.juce.com/t/juce-is-busted-in-xcode-11-4/38249/5)  in JUCE's `develop` branch. [the commit is here](https://github.com/WeAreROLI/JUCE/commit/dddeb1ad68f8539f5ea2fbac36c07532f12bf9cf)

## work around
just checkout `ext/juce` to `develop` from `5.4.1` (because the commit dddeb1 has not released yet)

## solution
when JUCE released new version which includes the commit, we need to update submodule `ext/juce` to latest

**Comment by nicochatzi** [comment]
The fix is in `6.0.0`. @nick-thompson are you ok with bumping a major version to close this issue?

**Comment by nick-thompson** [comment]
Yep, definitely. In conversation with @JoshMarler over the course of a few different PRs we're thinking that moving to JUCE6, C++17, and CMake will generally clean things up quite a bit.

If it's a seamless update from where we are now to 6.0.0 then we can go ahead and do it now. If it's messy, I wonder if it might be worth it to bite off the whole move to CMake at the same time.

@nicochatzi have you tried building the GainPlugin example after updating `ext/juce` to 6.0.0? Was it easy?

**Comment by emurray2** [comment]
I got the same error when I tried to build the GainPlugin example with Xcode 11.6(11E708) on macOS Catalina 10.15.6 . I replaced the existing folders inside `ext/juce` with the folders from my current JUCE directory. I have JUCE 6.0.1, and I was able to compile and run GainPlugin flawlessly!

Thank you all for the suggestions! I can't wait to learn more about this project and possibly contribute a bit once I figure things out.

**Comment by nick-thompson** [comment]
:+1: thanks! Definitely, we'll be making the update to juce6 asap.

@emurray2 I'd be happy to get you involved any time!

**Comment by emurray2** [comment]
Sounds good! Awesome, I'll keep you updated and take a look at the project tracker to see what I can work on.

**Comment by nick-thompson** [comment]
Done in 30fb81bc91cb5d9d2e0c2cc0319043042b57d67b!
