### ISSUE TITLE
Need to indicate node.js is a dependency in README.md

### ISSUE THREAD

**Issue by jrlanglois** [nick-thompson/blueprint#37]
Not having dealt with `npm` before, I can imagine others will be as confused as I was!

Also, I have no idea what this means if I want to bring my app to a different system to develop, let alone to just run. Say I'm in a sharing mood and want my friend to test out my app on their system - then what? Do they have to install node.js to run my app?

**Comment by nick-thompson** [comment]
Great point. Made me realize, I had written a better intro in the Wiki but never linked to it in the Readme, I'll change that :)

Here's the better guide: https://github.com/nick-thompson/blueprint/wiki/Getting-Started let me know if that one can be improved further. And yea, great question: Node.js and `npm` are only a development dependency; basically a compiler that takes in the js source code and emits a single "bundle." When you distribute your app all you have to do is send that bundle along with the binary, or for example, in your Release builds you can add the js bundle as a Binary Resource and it'll compile right into your plugin binary like normal. Then just point your `ReactApplicationRoot` to read the bundle string from BinaryData

**Comment by nick-thompson** [comment]
Ok readme is updated! I'm going to mark this as complete but please feel free to reopen if you think the readme needs further work
