### ISSUE TITLE
FR to pregenerate VS projects

### ISSUE THREAD

**Issue by jrlanglois** [nick-thompson/blueprint#39]
The Xcode project is pregenerated by the Projucer and committed to the repo. Would be nice to have the VS projects available as well. The purpose of JUCE is to be cross-platform so it would help get a better sense of the feasibility of this project without having to go through more hoops.

**Comment by nick-thompson** [comment]
💯 ! I work primarily on MacOS, which is the only reason there aren't VS projects in here. Blueprint is totally cross-platform-friendly. I'm totally happy to add them here or take a pull request that adds them

**Comment by nick-thompson** [comment]
As of #91 and #111 we've moved the examples to CMake, which has its own built-in generators for Xcode, VS, Make, etc. With that I think it's fair to go ahead and mark this closed. @jrlanglois feel free to reoopen if you disagree.
