### ISSUE TITLE
Optimize ShadowView::setProperty

### ISSUE THREAD

**Issue by nick-thompson** [nick-thompson/blueprint#4]
This method gets called a lot, and is pretty dominant in early profiling measurements. Need to dig into it, but off the top of my head I think there are gains to be made with:
* Making a struct of const identifiers for the comparisons so that we don't construct identifiers on every comparison in that call
* Early returns after the identifier is matched to avoid the remaining comparisons

**Comment by JoshMarler** [comment]
@nick-thompson, pretty sure we can close this one now too.
