### ISSUE TITLE
Add CMakeLists.txt to compile blueprint.cpp as static and/or shared libs

### ISSUE THREAD

**Issue by JoshMarler** [nick-thompson/blueprint#41]
Hi Nick, 

Currently using blueprint on linux in a CMake based build system. Would you be open to an MR with a simple CMakeLists.txt that effectively adds targets for a static and shared lib build of blueprint.cpp ? 

This could add something along the lines of

```
add_library(blueprint_static STATIC blueprint.cpp)
add_library(blueprint SHARED blueprint.cpp)

 target_include_directories(
  blueprint_static
  ./yoga
  ./duktape/src-noline
)
```

This would allow other CMake projects to simpy use something like the following to add blueprint:

```
add_subdirectory(../Libraries/blueprint/blueprint)
target_link_libraries(MyApp blueprint_static)
```

**Comment by JoshMarler** [comment]
Appreciate this could become more developed to add targets for the example plugins etc. etc.

**Comment by nick-thompson** [comment]
Definitely! I'm personally not too well-versed in CMake, but I totally understand its popularity. I'd be happy to include this to make the project more accessible to CMake users, and honestly I'd like to defer to you about how to best integrate with JUCE 6

**Comment by JoshMarler** [comment]
@nick-thompson, I think this should probably closed and we should create a new JUCE 6 CMake issue. Compiling to a static lib with juce isn't going to be a great option. Should have thought on that one a little more!
