### ISSUE TITLE
Undefined property access getPublicInstance

### ISSUE THREAD

**Issue by JoshMarler** [nick-thompson/blueprint#42]
Hi Nick. 

Trying to do some error troubleshooting and struggling with debugging. Looked into the duktape debugger integration but I expect a decent amount of work there to integrate nicely.

I'm seeing a bunch of "undefined property access" issues in my App component. Can't tell any significant changes that might have caused this. I've tried updating react-reconciler to latest but no joy. 

Any chance you could provide some info on how you track down the root cause of such errors in blueprint at the moment?

```Error: The above error occurred in the <App> component:
    in App

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
    at [anon] (/home/josh/development/inmusic/ACVS/Software/External/Libraries/blueprint/blueprint/duktape/extras/console/duk_console.c:49) internal
    at error () native strict preventsyield
    at logCapturedError (input:7958) strict
    at logError (input:7992) strict
    at [anon] (input:8858) strict
    at callCallback (input:3293) strict
    at commitUpdateEffects (input:3332) strict
    at commitUpdateQueue (input:3323) strict
    at commitLifeCycles (input:8219) strict
    at commitAllLifeCycles (input:9471) strict
    at [anon] (input:2111) strict
    [...]
MethodTrace: Stubbing undefined property access for getPublicInstance`

**Comment by nick-thompson** [comment]
Hey @JoshMarler 

Funny you write that, I was just pulling up the issues tab to log my own very related issue. The short story of it is that debugging in blueprint is _tricky_ right now and often I get by just through the use of console.logs. I really want to prioritize #11 but quite honestly I'm not sure how best to do it.

I'm facing a similar issue that I _think_ has to do with an updated version of ReactReconciler on `npm` that I just haven't written the support code for in the Blueprint HostConfig. That's the issue I was about to write but I might now call that a duplicate (of sorts) of this issue, and my suggestion now would be to take that same bundle that you're trying to execute in Blueprint and execute that bundle via Duktape directly with the `duk` command line tool with debugging enabled– see https://github.com/svaarala/duktape/tree/master/debugger#using-the-debugger-web-ui. In your case I suspect the debugger will catch attempting to invoke a method on an `undefined` or something, and we can trace that backwards to make the necessary edits in our Host config.

If you have the chance, give that a try, and I'm hoping to carve out some time to do the same. I'll write back here if I find anything!

**Comment by JoshMarler** [comment]
Hey Nick! 

As always thanks for the the speedy reply. I've got various pull requests on their way!

Ok awesome thanks for the heads up. I assumed it was some minor bump in the reconciler package. I might try rolling back a few versions just incase. Will give the debugger a try.

On a side note, I've been reading into the duktape transfer protocol and friends so if you're looking for some assistance I'd be happy to lend a hand. 

There's a decent looking duktape debug client extension for visual studio code that looks like it might be worth a look into. 

Cheers

Josh

**Comment by nick-thompson** [comment]
> On a side note, I've been reading into the duktape transfer protocol and friends so if you're looking for some assistance I'd be happy to lend a hand.

That would be so amazing!

**Comment by nick-thompson** [comment]
(FWIW: if you copy the `package-lock.json` from the `examples/GainPlugin/Source/jsui` directory, update the line for `file:../../` pointing to the blueprint package, and re-run `npm install` you'll grab a version of everything that works with the current Blueprint host config. At least that will unblock your current development for now)

**Comment by JoshMarler** [comment]
Awesome. Thanks Nick I'll give that a go for a moment so I can get a little further with this change and then try the cmd line debugger.

**Comment by JoshMarler** [comment]
Hey Nick. 

I managed to sort this out in the end. I'm using a slightly wonky approach in my experiments for our project which involves using yarn workspaces with a "Page" or App root/bundle per workspace. We have a number of pages which are essentially components owning a single bundle that represents the UI for the entire page. 

When a user changes mode they are taken to a new page. Workspaces make sense here as every bundle/page has the same set of dependencies, i.e. react, blueprint, babel. Using workspaces means we only need one copy of the various dependencies thanks to module loading and also allows us to use a very simple "yarn workspaces run build" in our CI script. 

Turns out a yarn.lock update was clashing with package-lock.json in blueprint. Reverting the lock update resolved the issue. 

I'm going to be digging into the duktape debugger support in earnest over the next week. I'll hopefully drop all of these pull requests I've got stacking up over to you early next week. 

I'd be interested to know if you think there is any sensible way to allow usage of yarn with blueprint etc (based on the situation I've described).

**Comment by JoshMarler** [comment]
I'll close this issue off now and drop some separate MR's.

**Comment by nick-thompson** [comment]
Thanks @JoshMarler ! To be honest, I'm totally unfamiliar with yarn workspaces, but yea that sounds cool. I'm sure there's a way to include yarn... maybe even just adding a yarnfile.lock next to the package-lock.json? That way whether you use yarn or npm we can guarantee a working set of dependencies?
