### ISSUE TITLE
Clean up the `nativeMethodWrapper`

### ISSUE THREAD

**Issue by nick-thompson** [nick-thompson/blueprint#43]
Commit 3811b0687d63059635254d8b7548abeec3a60877 introduces a better way to handle native method registration, used in the `pushVarToDukStack` and `readVarFromDukStack` methods to support passing e.g. a `DynamicObject` that has a `juce::var::NativeFunction` as a property.

The original `nativeMethodWrapper` is still lingering in there as used by the `registerNativeMethod` API, but it should be replaced with the newer stuff. See the TODOs inline: https://github.com/nick-thompson/blueprint/commit/3811b0687d63059635254d8b7548abeec3a60877#diff-9dd78235906a309d67f6d946b57e928fR17

**Comment by JoshMarler** [comment]
@nick-thompson, having spent a bunch of time around here over the last few days I'd be more than happy to give this a go. Would be great to be able to use capture blocks with the `registerNativeMethod` lambdas and get away from the stash dance. 

Let me know if you particularly wanted this one yourself and if not I'd be interested in taking it.

**Comment by JoshMarler** [comment]
Presumably we can kill of this when done: https://github.com/nick-thompson/blueprint/issues/29

**Comment by nick-thompson** [comment]
Resolved in e3d5057
