### ISSUE TITLE
Error compiling: invoke is not a member of 'std'

### ISSUE THREAD

**Issue by MinMiguelM** [nick-thompson/blueprint#45]
Hi, I am following the Starting a New Project guide and when I built I got the next error:

`blueprint/core/blueprint_CanvasView.h: In member function 'virtual void blueprint::CanvasView::paint(juce::Graphics&):
error: 'invoke' is not a member of 'std'
std::invoke(props["onDraw"].getNativeFunction(), nfargs);`.

I dont know if there is a missed step or there is an error there.

I'm using JUCE v5.4.7 on Ubuntu 16.04

Thanks in advance

**Comment by MinMiguelM** [comment]
Ok, I updated gcc to 7.5.0 and it fixed that problem but now I am getting other error:

blueprint/core/blueprint_GenericEditor.cpp:98:21: error: passing ‘const blueprint::ReactApplicationRoot’ as ‘this’ argument discards qualifiers [-fpermissive]
                     );
                     ^

**Comment by JoshMarler** [comment]
@MinMiguelM this might be fixed by the following PR: https://github.com/nick-thompson/blueprint/pull/47

**Comment by MinMiguelM** [comment]
yeah, a mutable lambda fixed, but now I am getting other error in duk_console, idk if probably the fix is already in the PR that you created, I will wait for it.

Thanks

**Comment by JoshMarler** [comment]
Hey @MinMiguelM, yeah I think hopefully that is fixed with those changes around duk_throw etc.

**Comment by nick-thompson** [comment]
:+1: thanks guys. @MinMiguelM I'll prioritize getting Josh's PR merged, let me know if it fixes your issues!

**Comment by MinMiguelM** [comment]
@nick-thompson , @JoshMarler 

I replicated those fixes and this error is throwing when I started app:

---------
Render started...
Error: {}
    at [anon] (/Builds/CLion/../../Modules/blueprint/blueprint/duktape/extras/console/duk_console.c:49) internal
    at error () native strict preventsyield
    at jn (eval:28) strict
    at [anon] (eval:28) strict
    at vt (eval:28) strict
    at ht (eval:28) strict
    at Vr (eval:28) strict
    at Br (eval:28) strict
    at Wr (eval:28) strict
    at Mr (eval:28) strict
    at cr (eval:28) strict
    [...]
**Blueprint Fatal Error:** uncaught: 'unsupported'
It is now unsafe to execute further code in the EcmascriptEngine.
terminate called after throwing an instance of 'std::runtime_error'
  what():  uncaught: 'unsupported'

**Comment by JoshMarler** [comment]
@MinMiguelM, it's probably worth confirming which app, i.e. is it one of the examples? Also you might want to run npm build in development mode to get an error with more context there. It looks like some js code that is probably doing something naughty. Suspect @nick-thompson can point you in the right direction. 

If I've broken an example app please let me know!

**Comment by MinMiguelM** [comment]
It is not an example, It is a new audio  plugin JUCE project.

Error in dev mode:

Render started...
Error: The above error occurred in the <App> component:
    in App

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
    at [anon] (/Builds/CLion/../../Modules/blueprint/blueprint/duktape/extras/console/duk_console.c:49) internal
    at error () native strict preventsyield
    at logCapturedError (input:7958) strict
    at logError (input:7992) strict
    at [anon] (input:8858) strict
    at callCallback (input:3293) strict
    at commitUpdateEffects (input:3332) strict
    at commitUpdateQueue (input:3323) strict
    at commitLifeCycles (input:8219) strict
    at commitAllLifeCycles (input:9471) strict
    at [anon] (input:2111) strict
    [...]
**Blueprint Fatal Error:** uncaught: 'unsupported'
It is now unsafe to execute further code in the EcmascriptEngine.
terminate called after throwing an instance of 'std::runtime_error'
  what():  uncaught: 'unsupported'

**Comment by nick-thompson** [comment]
Ok yea that's a different error, and probably a "high priority needs fixing" bug– something in the javascript dependency tree of Blueprint, something updated, and that thing no longer plays nicely with Duktape. This is blocking people from getting up and running with the project (I've seen this bug before), but it's a tricky one and will take me some time to find it.

In the meantime, @MinMiguelM the workaround that seems to work is to copy the `package-lock.json` file from the `GainPlugin` example directory, because that one locks down a set of dependencies that is known to work with blueprint. So, from your project, just `rm -rf ./node_modules`, `cp path/to/blueprint/examples/GainPlugin/Source/jsui/package-lock.json .` and then `npm install` again. Let me know if that works!

**Comment by MinMiguelM** [comment]
Yeap, it worked.

Let me know if I can help with anything, in the meantime I will try to find what dependency is making this happen.

Thanks

**Comment by nick-thompson** [comment]
Great! @MinMiguelM that would be super helpful.

I'll go ahead and close this then, as I think it's resolved now that #47 is merged. I'll open a new issue to track the javascript dependency bug
