### ISSUE TITLE
Optimize layout computation

### ISSUE THREAD

**Issue by nick-thompson** [nick-thompson/blueprint#5]
Right now the ReactApplicationRoot calls `performShadowTreeLayout` on every `setProperty` call. This is obviously overkill; in an ideal case we would run the shadow tree layout only once after the ReactRenderer update lifecycle has completed.

There are probably a couple ways to tackle this, but initially it looks like the renderer calls `resetAfterCommit` in the host config once it has finished committing updates to every affected child. I think we could defer the `performShadowTreeLayout` call to that hook...

**Comment by nick-thompson** [comment]
Quick note here: the React Native host config does not rely on `resetAfterCommit` to perform the layout step; `resetAfterCommit` is a noop there.

With that in mind, perhaps a reliable solution here is to continue calling `performShadowTreeLayout` from within `setProperty` or `addChild` etc, but in the case of setProperty only run the layout if the changed property is one of a predefined set that we know affects layout (i.e. don't run it if all we've changed is background-color)

**Comment by JoshMarler** [comment]
@nick-thompson, think it's fair to say we can close this which I shall do now. Reopen if you disagree.
