### ISSUE TITLE
JS Dependency Bug: "Unsupported"

### ISSUE THREAD

**Issue by nick-thompson** [nick-thompson/blueprint#50]
A fresh install of blueprint in a new project seems to pull in some dependency somewhere that uses a language feature unsupported by duktape:

```
Render started...
Error: The above error occurred in the component:
in App

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
at [anon] (/Builds/CLion/../../Modules/blueprint/blueprint/duktape/extras/console/duk_console.c:49) internal
at error () native strict preventsyield
at logCapturedError (input:7958) strict
at logError (input:7992) strict
at [anon] (input:8858) strict
at callCallback (input:3293) strict
at commitUpdateEffects (input:3332) strict
at commitUpdateQueue (input:3323) strict
at commitLifeCycles (input:8219) strict
at commitAllLifeCycles (input:9471) strict
at [anon] (input:2111) strict
[...]
Blueprint Fatal Error: uncaught: 'unsupported'
It is now unsafe to execute further code in the EcmascriptEngine.
terminate called after throwing an instance of 'std::runtime_error'
what(): uncaught: 'unsupported'
```

I think the best way to tackle this is probably (1) compile the duktape CLI tool with debugging support, (2) compile a `main.js` blueprint bundle with some shims for the native functions, then (3) run that bundle in the duktape CLI and try to catch with the debugger where the unsupported feaature is. Once we have located the bug we can figure out best steps to fix it

**Comment by JoshMarler** [comment]
@nick-thompson, this might be worth looking into now that we have debugging support enabled. Suspect mac will be the easiest platform to investigate on as Windows can be a bit of a faff at the moment.

**Comment by nick-thompson** [comment]
Yea this is my number 1 priority once debugging is in. I suspect it'll be relatively easy to spot under a debugger :). Just about to merge your PR there too, hopefully I can find some time to look at this over the weekend

**Comment by JoshMarler** [comment]
@nick-thompson, cool. If you want to farm it off give me a shout and I'll try to take a look. Will leave with you for the meantime.

**Comment by nick-thompson** [comment]
:+1: I've got a little time tonight to take a crack at it. I'll report back and probably hand it off to you if I don't make it anywhere :)

**Comment by nick-thompson** [comment]
Ok, got it, thanks to the debugger!

The `package.json` that we provide in the js template for new projects marks dependency versions with `^x.y.z`, which means that `npm` can satisfy them with anything newer than that version. Somewhere in the dependency tree, something updated and that update gets pulled in for new projects, introducing an `Array.from` call in the main code path, and Duktape doesn't support Array.from.

Babel has a polyfill that you can inject in your runtime for things like this, but in the early days of this project I found that polyfill to be waayyyy too slow for running React in Duktape. Also it always felt like a pain to add the extra step for end users to make sure the polyfill. Turns out babel has a plugin that applies this polyfill on the fly: https://babeljs.io/docs/en/babel-plugin-transform-runtime

With that I was able to blow away the `GainPlugin` node modules, reinstall them from the template package.json, and run everything just fine 🙌 . Fix will be on master shortly

**Comment by nick-thompson** [comment]
Fixed in d68987d5bd7fc36f339e826de7b6c9efd53aeee5

**Comment by JoshMarler** [comment]
Awesome! Nice one. Glad the debugger provided some value! Did you hit any issues with it ?

**Comment by nick-thompson** [comment]
I tried it out using the Duktape-provided web debugger, which admittedly leaves a lot to be desired, but I didn't yet get vscode set up to try it. Still, the only real issue was that this error happens on the first bundle eval, so I needed to CMD+D, then attach, then get the bundle to reload (which I did be rerunning `npm start`) but definitely that makes a nice case for a CMD+R reload the current bundle. Honestly though, for that to be the only pain point after all the work that went in to #61, I'm thrilled

**Comment by JoshMarler** [comment]
Ahh OK fair enough. Yeah cool. Tell you what. I'll drop you a CMD+R reload over the weekend if I can!

**Comment by nick-thompson** [comment]
Ah that'd be awesome, thanks!
