### ISSUE TITLE
Add Typescript definitions/support

### ISSUE THREAD

**Issue by JoshMarler** [nick-thompson/blueprint#51]
It would be great to add TypeScript definitions/support to Blueprint. Strong types will be a familiar warm blanket for less JS savvy C++ devs.

Being able to define interfaces and the like for component properties will help with avoiding errors at compile time (View would certainly benefit from this addition). It's inherently a little more complex to debug type mismatches and referencing undefined  vars in Blueprint.

**Comment by nick-thompson** [comment]
💯 love the idea! I think `View` is a great place to start, and after #44 and #43 go in, the `View` API should be pretty stable, so sounds like great timing

**Comment by nick-thompson** [comment]
Marking this as closed after #99. We're now generally moving ahead with typescript support, and as the APIs are stabilizing so too will the type defs. Huge thanks to both @JoshMarler and @rbaxter08– I really appreciate it guys!
