### ISSUE TITLE
Support `getTransform` in `CanvasView`

### ISSUE THREAD

**Issue by nick-thompson** [nick-thompson/blueprint#52]
Per the discussion [here](https://github.com/nick-thompson/blueprint/pull/49#discussion_r429548431) in #49, we're working to implement a shim of the [CanvasRenderingContext2D](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D) API such that from javascript you can draw with something that feels exactly like working on a `<canvas/>` in web, but actually draws natively via JUCE's Graphics routines.

This particular task is for implementing the transform stack in such a way that we can satisfy the `getTransform` [method](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/getTransform) by matrix multiplication over a series of `juce::AffineTransform` matrices, as described in the discussion linked above

**Comment by JoshMarler** [comment]
@nick-thompson , Can I suggest we close this issue and just make it part of https://github.com/nick-thompson/blueprint/issues/48 ? I'll add a checklist on there now with the minimum API coverage we discussed for beta and `getTransform` will be included in that list.

**Comment by nick-thompson** [comment]
Yup, sounds good!
