### ISSUE TITLE
Blueprint "extras" module

### ISSUE THREAD

**Issue by JoshMarler** [nick-thompson/blueprint#53]
It would be great to create a new blueprint-extras or blueprint-components repo/module which provided users with a set of reusable components to get up and running. 

For example, blueprint-extras could supply a generic <Slider> implementation which handles value changes etc. This component could work in a similar fashion to juce::Slider and still allow users to customise the slider's behaviour with onDraw, onValueChanged props etc. 

Part of this "extras" module could also include juce-wrapper components as discussed here: https://forum.juce.com/t/introducing-blueprint-build-native-juce-interfaces-with-react-js/34174/25

@nick-thompson I'd be interested to hear your thoughts about this in regards to how such a project could be kicked off.

**Comment by nick-thompson** [comment]
Yes! I meant to mention this in our conversation, but looking back over our chats I obviously forgot :)

At the root of the current repository is a `blueprint/` directory holding the "blueprint core juce module." Right now, especially as blueprint continues to evolve quickly and as the "extras" module grows, I think it makes sense to just keep it right here– probably just a `blueprint_extras/` directory at the root, with its own JUCE Module stuff. As its own module, it will maintain its independence, and if at some point it makes more sense to move it out into its own repo it'll be a trivial task

What do you think? I think your `juce::Slider` wrapper from our forum discussion is a great first add, and a "slider example" project to show the different approaches would probably be super helpful

**Comment by JoshMarler** [comment]
Yeah that sounds like a great start to me!

**Comment by JoshMarler** [comment]
I'll be writing a couple of "generic" component classes over the next few days for my current project so once I'm happy with them I'll be sure to send a PR across with this.

**Comment by nick-thompson** [comment]
Great, excited to see it! Thanks

**Comment by nick-thompson** [comment]
Picking this back up after a great convo in #70 

Structurally, I imagine this work residing in two places: on the native side, we'll create a new JUCE Module, `blueprint_extras` right next to the `blueprint` module at the top level of this repo. This module should have a dependency on the core `blueprint` module. Next, we'll have the javascript side in a new package next to `packages/juce-blueprint` maybe just called `packages/blueprint-extras` (we'll be undergoing a big rename following #34 presumably, so names don't matter so much here right now).

On the native side, we're thinking about some free-standing helper functions for registering native methods bound to a `juce::AudioProcessorValueTreeState`: https://github.com/nick-thompson/blueprint/issues/70#issuecomment-655545516. We're also thinking about those native components mentioned above which wrap specialized juce components such as `juce::Slider` and have a nice LookAndFeel layer for delegating to JS paint methods and such.

On the js side, we'll have the corresponding APIs and Components for the native work just mentioned, as well as pure-js components such as `ParamSlider` (mentioned in #70) that compose a `Slider` from the blueprint core library and add some specialized hooks to those APIs registered to the `AudioProcessorValueTreeState`.

I believe that's a comprehensive overview, and obviously a big task which will likely have to be broken down into stages.

**Comment by JoshMarler** [comment]
@nick-thompson, think this captures the scope of the issue perfectly. 

Also worth noting if it's not clear from the link that we may add a couple more exotic components to the `extras` module like `FrequencyResponsePlot` or `WaveformPlot` etc.

**Comment by JoshMarler** [comment]
@nick-thompson 

I've just about got an initial set of base components together and I'm working on fleshing out the ParameterValueStore/AudioProcessorValueTreeState stuff. 

It'd be cool to get this "extras" package going soon. Noticed you'd gotten a bit of interest on the forum again etc. 

Just to clarify, are we thinking add the new module and packages directly to this repo ? I.e.no need to got submodule them or anything ? If so I could start getting a thing together and drop your a PR with a structure idea and some initial components. Let me know what you think. Cheers

**Comment by nick-thompson** [comment]
Awesome. Yea people are asking for it :)

> Just to clarify, are we thinking add the new module and packages directly to this repo ?

Yea, I think that makes sense for now. No need to complicate the workflow with more submodules or anything before it becomes necessary.

**Comment by JoshMarler** [comment]
Awesome. I'll aim to get you a PR over for the weekend. Has Button, ToggleButton, Slider and possibly Picker as a start Then wrappers like ParamButton, ParamSlider etc. 

Hopefully we can chat over the base component approaches. At the moment I quite like a Canvas approach with drawFunction props and default implementations of those draw functions of no override provided. Has worked really well in my case but we'll see what you think to the overall shape when I get it over. 

I like it because it's easy to pull in an SVG document inside the drawFunction thanks to the drawImage API etc.

Cheers

**Comment by JoshMarler** [comment]
@nick-thompson, I realise I've still not dropped this across. Mainly because I've been refining various things after more experience building out a UI with these core components. 

I'm starting to look at moving the `basic-components` folder from my current React/Blueprint app into Blueprint. 

Very quick question, organisation wise, where should Blueprint's core components live? `juce-blueprint/esm/components` ?

I'll start trying to get this together over the weekend. My current components are .tsx components so I'll split them back to plain JS with type definition files as per our chat on Discord the other day, I don't think enforcing Typescript too heavily is a good idea at all right now.

**Comment by nick-thompson** [comment]
Great! Yea let's move to #70 but I'll answer here briefly:

> Very quick question, organisation wise, where should Blueprint's core components live? `juce-blueprint/esm/components` ?

Yep sounds good to me.

> I'll start trying to get this together over the weekend. My current components are .tsx components so I'll split them back to plain JS with type definition files as per our chat on Discord the other day, I don't think enforcing Typescript too heavily is a good idea at all right now.

Agreed, thanks! I think we'll have to strike the right balance with typescript right now. Things will still be changing fast enough that I don't want to go all in on it yet, plus I think we have some work to do on first-time-user experience still

> Also, I've followed this whole approach of using Canvas draw functions for the majority of components. They have a basic draw implementation and that can be overridden by user paint functions (ala juce::LookAndFeel). I've got various little simple canvas draw helpers in a lib. i.e. `drawRoundedRect` etc. Is this something worth sticking in Blueprint? i.e. some DrawingHelpers.js in the lib directory or similar? There may be libraries you're aware of that we could leverage for this? Alternatively that can just be a thing we leverage internally for these components?

Yea interesting. I think it'd be helpful to see the code; I could imagine some drawing utilities being helpful, but I could also imagine integrating a third party library for drawing utilities if the CanvasContext API has parity enough.

I also had a thought the other day about this– one thing that I'm realizing I hesitate about a little bit, in terms of deriving these core UI components from Canvas, is that it means that a larger application will lean very heavily on the javascript engine within the paint loop. For example, an app with many buttons, toggle buttons, and sliders: what happens in the event of resizing the window? I'd be interested to measure the performance impact. On the flip side, a Button derived only from `View` using `style` primitives (background-color, border-radius, etc), never has to visit the JS engine during a paint loop. So a larger app during a big event like a resize will lean less heavily on the js engine. Obviously, as this is mostly an optimization question, there's not much to do here before we measure :)

Let's move this to #70 but yes, very happy to start looking at what you've got!

**Comment by JoshMarler** [comment]
@nick-thompson , I think this issue can probably die for now. It existed before we decided that the likes of `Slider` and `Button` would just live in blueprint core. We can revisit at a later time if needed but makes sense to keep list of issues clean whilst we run to beta.
