### ISSUE TITLE
Implement a full Duktape Debugger Transport

### ISSUE THREAD

**Issue by nick-thompson** [nick-thompson/blueprint#63]
Sparked from discussion in PR #61: https://github.com/nick-thompson/blueprint/pull/61#discussion_r440878576

To implement debugging with Duktape we're using their `debug-trans-socket/duk_trans_socket_unix.c` implementation with a little hack for preventing SIGPIPE issues. Their implementation seems to refer to itself as not production quality, so the task here is to revisit this debugger transport and implement whatever updates we may need to make it effective and robust

**Comment by JoshMarler** [comment]
@nick-thompson, this probably doesn't need to be beta. Correct me if I'm wrong.

**Comment by nick-thompson** [comment]
:+1:
