### ISSUE TITLE
Distinguish Errors and Fatal Errors

### ISSUE THREAD

**Issue by nick-thompson** [nick-thompson/blueprint#64]
Sparked from conversation in PR #61: https://github.com/nick-thompson/blueprint/pull/61#issuecomment-644797255

In Duktape we have sort of two classes of errors: normal errors from which we can recover the js engine, and fatal errors from which we cannot. A normal error that goes uncaught becomes a fatal error, and so do explicit fatal cases from within Duktape itself. In ReactAppRoot we can catch almost all errors by making sure we do everything inside `duk_pcall` wrappers, and when we catch those errors we pop up the red stacktrace screen and wait for the user to update the bundle. This works great in dev, but we need a way to let the user define a custom error handler override so that, for example, they don't ship this red stacktrace screen in production. 

Then we need a second override (or perhaps just a flag to the former override) to distinguish for cases where we're dealing with a fatal error, which I anticipate being rare cases, but cases we need to cover. I think it's fair for our default implementation to be just throwing a C++ error and crashing out, but obviously users should be able to customize that behavior.

**Comment by JoshMarler** [comment]
Yeah this covers this nicely. Personally I'm for the flag argument to the existing onUnhandledError callback/override.

**Comment by nick-thompson** [comment]
:+1: I think I lean the same way!

**Comment by nick-thompson** [comment]
Resolved in e3d5057
