### ISSUE TITLE
Refine the "Multiple Bundles" story/behaviour

### ISSUE THREAD

**Issue by JoshMarler** [nick-thompson/blueprint#65]
There are numerous areas of code in `ReactApplicationRoot` and `EcmascriptEngine` which may need to behave differently when blueprint supports the loading/evaluation of multiple bundles, i.e. for polyfill behaviour etc. 

In particular, things like error handling and hot-reloading will need careful consideration. If a single bundle causes and evaluation error, does this mean we need to reload all bundle? There may be cases for tracking/storing the bundles loaded by callers etc. 

Initially it might be good to define what all the use-cases of multiple bundle evaluation are and go from there.

**Comment by nick-thompson** [comment]
:+1: Definitely. Do you think it's fair to move forward for now assuming everything is a single bundle? Until we hit a first concrete case for multiple bundles? I can guess at a few cases where multiple bundles might come in handy, but I can't make any promises that anybody will actually use it :)

**Comment by JoshMarler** [comment]
Yeah. I've been hitting thoughts/considerations around multiple bundles a lot whilst looking at hot-reload and debug support. It's less pressing now I'm abandoning the idea of not resetting EcmascriptEngine in the event of a reload/error. 

I made the BundleWatcher class in ReactApplicationRoot able to handle multiple bundles for the sake of some "forward planning". I think it makes sense to assume users will load single bundles for the moment. For an initial Beta release maybe it makes sense to document this, i.e. Blueprint currently only supports loading a single bundle per ReactApplicationRoot/EcmascriptEngine instance. 

It's then probably a thing thought should just be considered and kept in the back of our minds during Blueprint development. i.e. we want to at least attempt to keep multiple bundles a possibility in the future and not make it an impossible task down the line.

**Comment by nick-thompson** [comment]
Done as of #137!
