### ISSUE TITLE
ListView Component

### ISSUE THREAD

**Issue by nick-thompson** [nick-thompson/blueprint#71]
See #70 

This task is to track the implementation of a `ListView` component, similar to React Native's [FlatList](https://reactnative.dev/docs/flatlist). In particular I'm interested in providing a `ListView` implementation that can handle rendering large lists efficiently by only rendering visible content and not allocating thousands of `blueprint::View`'s that are not shown. I anticipate this involving a `ScrollView` somehow and may need some clever native component

**Comment by nick-thompson** [comment]
Coming back to lay down some more thoughts on this. Generally, my view on this component is: let's do the simplest thing first.

In my head, `ListView` could really essentially be just a ScrollView with a bunch of Views inside of it. For example...

```
class ListView extends Component {
  render() {
    return (
      <ScrollView>
        <ScrollView.ContentView>
          {this.props.children}
        </ScrollView.ContentView>
      </ScrollView>
    );
  }
}
```
and the user of such a component would just do
```
<ListView>
    {this.props.items.map(function(item) { return <View><Text>{item.text}</Text></View> })}
</ListView>
```
or whatever they want.

In practice, if that were our only goal here, I would maybe push for not even adding a ListView component to the core library, since it's easy enough for a user to write themselves. Of course, that's not the only goal.

My intention for a ListView component is for the case where the above implementation crumbles under load. Imagine a sample browser implemented above with thousands of samples. Can the above implementation handle it? What does it cost us from a performance perspective? In the above implementation, we would be rendering thousands of `View`'s that the user can't look at at one time. Is there a need for performance optimization there?

So, what I envision is something like this:

```
<ListView>
  {this.props.samples.map(function(sample) {
    return (
      <ListView.Item><Text>{sample.name}</Text></ListView.Item>
    );
  });
</ListView>
```
Internally, `ListView` is maybe a composition over a `ScrollView`, or maybe it's a native component with an implementation quite like the native `ScrollView` component. `ListView.Item` is likely just a `View`.

With that, let's render a list of 10k items and see how it feels, measure the CPU. I suspect (1) the js side of that will be sluggish, and a `shouldComponentUpdate` will become extremely important. (2) Drawing all those views out of bounds of the parent will be sluggish. Maybe there's a win there to just only `addAndMakeVisible` the child views that we know to be within the bounds of the scrollview (+ a little extra on either side for smooth scrolling).

If these hunches are wrong, or if that don't get us reasonable rendering for 10k elements, we might have to go back to the drawing board. I have some ideas for this case as well, but I don't want to go down this path until we know we need to.

**Comment by JoshMarler** [comment]
@nick-thompson, This is excellent thanks for the ideas. OK. I'll compose a very simple `ListView` initially in the component demo app that I'm building and get us some metrics using a dumb ScrollView. Then I can look at the state of the world with large object lists and have a look at the second implementation approach. Leveraging `addAndMakeVisible` based on child `View` sizes and scroll position sounds like a nice first attempt. 

Will tackle this over the weekend and let you know how things go.

**Comment by JoshMarler** [comment]
@nick-thompson, I'm going to look at this in my next sprint from Monday.  I suspect this is going to become important for us as we'll have cases where I may switch between 2 reasonably large lists of elements based on some category filter or similar. i.e. get all samples from library A, get all samples from library B. In this instance a virtualized list is going to be really important. 

I have a simple scroll view implementation at the moment so I'll render 10k items rather than my current 500 and get some metrics and then imitate a "category switch" to render the list again with an alternate set of items. I suspect performance will crumble at this point. 

Could you just clarify where you envisage the use of `shouldComponentUpdate` helping here? On the `List.Item` components?

**Comment by nick-thompson** [comment]
Awesome, yea, this will be a good test :)

I think `shouldComponentUpdate` on the top `ListView` will be ideal: best not to even try rendering/reconciling 10k children if the props at the `ListView` level haven't changed.

Another thought that I'm just having right now– it might be best, at the time that you switch from A to B or vice versa, to only re-render with the first ~50 items. Maybe the new `this.props.samples` is only 50 items at that point. Then the render-on-switch cost will be mitigated, and you could do something like in `componentDidUpdate` check if you just made a switch and only have 50, and if so, do a `setState` to load the next batch. Still might get really sluggish as that list of children gets into the thousands, but wonder if it would help

**Comment by JoshMarler** [comment]
@nick-thompson , another one that probably doesn't need to be beta. Will remove and correct if you think it should be.

**Comment by nick-thompson** [comment]
Right that makes total sense. @JoshMarler I'm going to mark this as assigned to you while you're on it to hopefully prevent duplicate work. And I'll add a `CONTRIBUTING.md` file shortly to clarify that workflow!

**Comment by nick-thompson** [comment]
Adding this to the beta milestone as we're already almost there #192 !

**Comment by nick-thompson** [comment]
Done in #192!
