### ISSUE TITLE
Slider Component

### ISSUE THREAD

**Issue by nick-thompson** [nick-thompson/blueprint#74]
See #70 

A `<Slider>` component for the core blueprint component library. See @JoshMarler's comment here: https://github.com/nick-thompson/blueprint/issues/70#issuecomment-655589766 for the direction we want to go with this to allow maximum flexibility for the end user

**Comment by JoshMarler** [comment]
Done as of https://github.com/nick-thompson/blueprint/commit/fe917396539679db2e5db0a50e9d5784184c9f9d
