### ISSUE TITLE
Property 'assign' does not exist on type 'ObjectConstructor'

### ISSUE THREAD

**Issue by betterthanclay** [nick-thompson/blueprint#77]
I'm just running through the getting started guide but am unable to build the JS library by default with the following error:

```
esm/Blueprint.ts:133:53 - error TS2339: Property 'assign' does not exist on type 'ObjectConstructor'.

133     return React.createElement('CanvasView', Object.assign({}, this.props, {
                                                        ~~~~~~
```

The assign() call signature used above is an ES6 feature but you're currently targeting ES5. Switching the target in your tsconfig.json file to "es6" allows the project to compile fully.
Info here - https://stackoverflow.com/a/36304926

The npm output also includes this error immediately after, though it's likely just fallout from the first:

```
node_modules/@types/react/index.d.ts:417:23 - error TS2583: Cannot find name 'Set'. Do you need to change your target library? Try changing the `lib` compiler option to es2015 or later.

417         interactions: Set<SchedulerInteraction>,
                          ~~~
```

I'm on:
- Mac High Sierra 10.13.6
- Node 14.5.0 (homebrew)
- JUCE 6.0.1
- Xcode 10.1

**Comment by nick-thompson** [comment]
Ah oops, thank you for the report! I'm new to typescript, apologies for the hiccup there. I'll get that fixed ASAP

**Comment by nick-thompson** [comment]
Fixed in f76601e527fffb85c9893dcd098326fdc6a77b6d. Thanks!

**Comment by betterthanclay** [comment]
Thanks Nick, no worries, there are _plenty_ of gotchas with JS + TS in this context, easy one to miss.
The project is looking great and doing some really useful stuff - I'm looking to use it on a couple of different things that I'm going to be working on over the next few months, I'll see if I can offer anything useful into the mix if I can.

**Comment by nick-thompson** [comment]
Awesome, that would be great!
