### ISSUE TITLE
ReactApplicationRoot::dispatchEvent add juce::NativeFunctionArgs or std::vector<juce::var> overload

### ISSUE THREAD

**Issue by JoshMarler** [nick-thompson/blueprint#80]
@nick-thompson, 

I'm hitting a case in my current project where it would be useful to have a `ReactApplicationRoot::dispatchEvent` overload which takes a dynamic set of "runtime" arguments. Currently `dispatchit's a parameter pack 

Now, it's arguable that this is a code-smell/result of my data-model design. What do you think, would you say some interface along the lines of the below would be valuable?

`ReactApplicationRoot::dispatchEvent(const juce::String &eventTypes, const juce::var::NativeFunctionArgs &eventArgs)`

`ReactApplicationRoot::dispatchEvent(const juce::String &eventType, const std::vector<juce::var> &args)`

**Comment by nick-thompson** [comment]
Hmm I think that brings up an interesting question, what would you expect the arguments on the javascript side to look like given a function signature like that on the native side? For example, if I call the `ReactApplicationRoot::dispatchEvent(const juce::String &eventType, const std::vector<juce::var> &args)`, should I expect my event callback in javascript to receive a single array-type argument? In that case, if you call the existing `dispatchEvent` with a `juce::Array<juce::var>&` it should correctly propagate already (because `juce::var` has a constructor for that– https://docs.juce.com/master/classvar.html#aaee0a5c918953159d4f461db8e6f82ff)

**Comment by JoshMarler** [comment]
That's very true I could indeed use a juce::Array .... hmmm.

I guess I was thinking of it as a direct entry point to this overload:

`juce::var EcmascriptEngine::invoke (const juce::String& name, const std::vector<juce::var>& vargs)`

i.e. each arg from the vector passed to `ReactApplicationRoot::dispatchEvent` would be passed through individually and if `args[0]` is a `juce::var` constructed from an array it is passed to js as such. 

In my case I could have React/JS handle the event args as a single array argument and iterate through that but it feels a bit clunky. I'd rather get a function signature with individual args as documented by my API. 

I basically have a `DataModel` type of class interface with "properties" and "events". You can register listeners to individual properties and events. In the case of an event the Listener class implements a callback like the below:

 `HandleEvent(const juce::String &eventID, const juce::var::NativeFunctionArgs &args)`

The "Listener" in my case is basically a `juce::Component` which takes this abstract `DataModel` interface in it's constructor and binds event and property changes in the data model to calls to `ReactApplicationRoot::dispatchEvent` etc. Then I have `beginPropertyChangeGesture`, `setPropertyChange` functions  registered similar to your flux style approach.  

Ideally I'd have some event `setInstrumentVolume` handled in React which takes to args `instrument`, `volumeLevel`.

**Comment by nick-thompson** [comment]
Oh, of course. I forgot we had distinctions for this in `EcmascriptEngine`.

I'm realizing now, I think we should rename those overloads in EcmascriptEngine. The parameter pack should be called `call` and the vector should be called `apply`, matching the expected behavior as in javascript itself.

Then, yea, given these overloads I think it makes sense to extend the interface to `dispatchEvent`. In that case, wondering if it would make sense to name them as follows:

```
ReactApplicationRoot::callDispatchEvent(juce::String const& type, Ts... args);
ReactApplicationRoot::applyDispatchEvent(juce::String const& type, std::vector<juce::var>& args);
```

What do you think? (I prefer `std::vector<juce::var>` over `juce::var::NativeFunctionArgs` where we can because the `NativeFunctionArgs` are much more of a pain to use)

**Comment by JoshMarler** [comment]
So with the `apply` approach are we expecting the function signatures in JS to take singular args as per the below example?

```
var person = {
  fullName: function(city, country) {
    return this.firstName + " " + this.lastName + "," + city + "," + country;
  }
}
var person1 = {
  firstName:"John",
  lastName: "Doe"
}
person.fullName.apply(person1, ["Oslo", "Norway"]);
```

i.e. do we just apply spread operator in EventBridge or something? 

If so that sounds good to me and yeah I think a `std::vector<juce::var>` is the nicest interface.

**Comment by JoshMarler** [comment]
More than happy to tackle this by the way as I could do with it for me interface. Just need to clarify how that `apply` behaviour should work with the `EventBridge`

**Comment by nick-thompson** [comment]
So `EcmascriptEngine::invoke(const juce::String& name, const std::vector<juce::var>& args);` already implements the equivalent of javascript's `Function.prototype.apply`: it accepts a list of args and unrolls them onto the arg stack in duktape: https://github.com/nick-thompson/blueprint/blob/master/blueprint/core/blueprint_EcmascriptEngine.cpp#L272.

The other `invoke` overload with the parameter pack effectively implements javascript's `Function.prototype.call`, but with a little trick through the other interface: https://github.com/nick-thompson/blueprint/blob/master/blueprint/core/blueprint_EcmascriptEngine.h#L171

The existing `ReactApplicationRoot::dispatchEvent` is adopting the `Function.prototype.call` behavior by using `std::forward` to move the parameter pack into the parameter pack overload of EcmascriptEngine's `invoke`. I was thinking that if we added `ReactApplicationRoot::dispatchEvent(const juce::String& eventType, const std::vector<juce::var>& args)` we would implement it by just calling through to the `EcmascriptEngine::invoke(const juce::String& name, const std::vector<juce::var>& args)` interface, thereby providing the user with the option to effectively "call" or effectively "apply" from C++ when dispatching an event (which I believe is what you're looking for). Does that make more sense?

**Comment by JoshMarler** [comment]
Right. Yep I understand, thanks Nick. Happy for me to have a crack at adding these new signatures then?

**Comment by nick-thompson** [comment]
Yea, please!

**Comment by JoshMarler** [comment]
@nick-thompson, quick one. 

To directly use the `std::vector<juce::var` overload of `engine.invoke` we would need to insert `eventType` at the front of the `args` vector passed in. This feels pretty inefficient for things like timer based updates, i.e. a meter or something. 

What do you think is the better approach here? Do we just document that the user needs to supply the `eventType` as the first element of the `args` vector?

**Comment by JoshMarler** [comment]
Hmm. After writing that this still all feels a bit clunky ...

**Comment by JoshMarler** [comment]
There might actually be some value in using `juce::var::NativeFunctionArgs` to avoid some copies as it could allow optimisations in some cases

i.e.

```
    template <typename... T>
    void DataModelEvent::RaiseEventFromModel(T... eventArgs)
    {
        constexpr size_t numArgs = sizeof...(T) + 1;
        std::array<juce::var, numArgs> vArgs = {GetEventID(), eventArgs...};
       
        Notify(&DataModelEventListener::HandleEvent, GetEventID(), juce::var::NativeFunctionArgs(
                                                                                                                juce::var(),
                                                                                                                vArgs.data(),
                                                                                                                vArgs.size()));
    }
```
Some ugliness there with duplication of eventID in the arg pack but I'm still mulling around some designs.

**Comment by JoshMarler** [comment]
I was also wondering if the vector allocation her gets optimised away or not in all cases:

```
    template <typename... T>
    juce::var EcmascriptEngine::invoke (const juce::String& name, T... args)
    {
        // Pack the args and push them to the alternate `invoke` implementation
        std::vector<juce::var> vargs { args... };
        return invoke(name, vargs);
    }
```

I think C++14 does allow it but it's a compiler implementation detail. I wonder whether it would be worth considering:
```
    template <typename... T>
    juce::var EcmascriptEngine::invoke (const juce::String& name, T... args)
    {
        // Pack the args and push them to the alternate `invoke` implementation
        std::array<juce::var, sizeof...(args)> vargs;
        return invoke(name, vargs);
    }
```

**Comment by nick-thompson** [comment]
Ahh, interesting, didn't think about that.

Ignoring performance optimizations for a minute, what do you think the ideal API here is?

```
// We have already:
ReactApplicationRoot::dispatchEvent(eventType, ...args);
// Then we could add:
ReactApplicationRoot::applyDispatchEvent(eventType, vector<args>);
// Or...
ReactApplicationRoot::applyDispatchEvent(vector<args>);
```

I guess I'd hesitate to make things too complicated, because C++ feels just kind of unfriendly here. For example, this is still valid with the current API:

```cpp
void onDataModelEventRaised(const std::vector<juce::var> &args) override
{
    // Push some change from our generic DataModel interface into the relevant React/JS app.
    appRoot.dispatchEvent("modelChange", juce::Array(args.data(), args.size()));
}
```

Of course here, on the javascript side, you'll receive your arguments as an array:

```js
EventBridge.addListener('modelChange', function(argsArray) {
});
```

But javascript is just more friendly in this game:

```js
EventBridge.addListener('modelChange', function(argsArray) {
    myActualHandler(...argsArray); // or myActualHandler.apply(null, argsArray);
});
```

So... when it's trivially easy on the javascript side I feel like it's best to not overthink the C++ side. So, with that in mind, circling back to `ReactApplicationRoot` I'm not quite sure which way I feel is best

**Comment by JoshMarler** [comment]
Yeah this is sort of how I thought it would be implemented initially until you made the good point about the whole `Function.apply` like behaviour.

**Comment by JoshMarler** [comment]
Ooops. I didn't mean to close that!

**Comment by nick-thompson** [comment]
> Yeah this is sort of how I thought it would be implemented initially until you made the good point about the whole `Function.apply` like behaviour.

Yea definitely. The `Function.apply` behavior made more sense before I thougth about prepending the eventType as you mentioned heh.

> To be honest, given vector<> is a potential performance hole and given neither of the other two options are ideal, I'm wondering if this is best left alone for now and handled in JS as you've suggested. Perhaps the whole `juce::NativeFunctionArgs` overload in `EcmascriptEngine` is a thing best left for a later investigation.

:+1: I'm with you. I think when we have a solid notion of "feature complete" or at least "feature complete for beta" we'll want to take some time to perf audit. I know for sure we have some low hanging fruit elsewhere, but I could imagine this one showing up in the profiler.

> I'll have a quick go with that approach now.

Let me know how it goes. If you end up liking the approach, we can close this issue out or rename it to track the performance audit for later

**Comment by JoshMarler** [comment]
Yeah the approach is fine for the meantime I think. Lets close it. Perf session after beta sounds good to me.

**Comment by nick-thompson** [comment]
:+1: Sorry to run you around on this!

**Comment by JoshMarler** [comment]
>  Sorry to run you around on this!

Not at all! Is great to discuss these things, even if the only useful thing that came out of it was a potential performance improvement! 

If anything I'm the one chewing your ear of whilst I experiment with different designs.
