### ISSUE TITLE
Support JUCE 6 CMake builds

### ISSUE THREAD

**Issue by JoshMarler** [nick-thompson/blueprint#91]
We should investigate what needs to be done to better support JUCE 6 and the new cmake builds system.

**Comment by JoshMarler** [comment]
So I've just been using JUCE 6 cmake finally for some of our stuff. 

Basically there's very little to do by virtue of blueprint being a juce module. People should pretty much just do the following in their CMakeLists.txt as I understand it:

```
juce_add_module(/path/to/blueprint/blueprint)
target_link_libraries(MyApp PRIVATE blueprint)
```

I reckon it'd be cool to just add a CMakeLists.txt to the example project. I'll drop something over this eve. That can act as a sanity check to ensure that adding blueprint just requires the above addition for people on JUCE 6. 

@nick-thompson, I don't really know anything about the PIP file approach but I shall have a look into it!

**Comment by nick-thompson** [comment]
Wow, awesome, that all sounds great. I think a toplevel CMakeLists.txt is a great idea, and if we can configure it such that we can build all the example projects easily then I think our continuous integration plan will be dead simple. These are both high on my priority list.

Don't worry too much about the PIP file, it's an "oh that'd be pretty neat" but there are plenty of better things to spend our time on hahah

**Comment by JoshMarler** [comment]
Yeah awesome. I can set that up easy I reckon. Will have a crack at it tonight.

**Comment by discordance** [comment]
Had to add this into my project CMakeList to compile (I installed blueprint as a submodule).

`# look for blueprint headers
target_include_directories(MyProj
    PRIVATE
    ./libs/blueprint/blueprint
    ./libs/blueprint/blueprint/yoga
    ./libs/blueprint/blueprint/duktape/src)`

**Comment by nick-thompson** [comment]
Done as of f41ee5d6aa20ffa32031a50ac62de4aad3b7dfb6!
