### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by colshacol** [nick-thompson/blueprint#93]
I see that the API docs say they are a WIP, but they are absolutely critical! Although I am no C/C++ developer, I can read a lot of the code and would like to potentially assist in helping with this documentation if you could point me in the right direction to find APIs that are exposed to the JS runtime.

I’d like to find out where the events provided by EventBridge are implemented and focus on documenting those, if not more than that.

🙏🙏🙏

**Comment by nick-thompson** [comment]
Okay, happy to report that I've got a better documentation system going!

The docs site is live here: https://nick-thompson.github.io/blueprint/#/
And it's all served via Docsify from within the `docs/` folder in the root of the repository.

I'll do my best to keep updating it, but I'll also very happily welcome your help if you're interested :)

**Comment by nick-thompson** [comment]
I'm going to close this and roll it into #12 where we will more actively track what docs need to be done, and then get working on it.
